In [1]:
import pandas as pd
import numpy as np
import math

characters =['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',' ']
language = ['e','j','s']

def read_file(filename, path = './languageID/'):
    file = open(path+filename, 'r')
    file_content = file.read()
    file_content = file_content.replace('\n', '')
    return file_content

def index(c):
    if c == ' ':
        return 26
    else:
        return ord(c)-ord('a')

def count_character(file):
    c_count = []
    l = len(file)
    for i in characters:
        count = 0
        for j in range(l):
            for k in file[j]:
                if i == k:
                    count+=1
        c_count.append(count)
    return c_count


In [2]:
e_list=[]
j_list=[]
s_list=[]
for i in range(10):
    e_list.append(read_file("e"+str(i)+'.txt'))
    j_list.append(read_file("j"+str(i)+'.txt'))
    s_list.append(read_file("s"+str(i)+'.txt'))

### (2)

In [3]:
# Q2
df = pd.DataFrame(characters, columns=['characters'])
# theta_e
df['e_count'] = count_character(e_list)
total_e = sum(count_character(e_list))

theta_log_e = [math.log(count_character(e_list)[i]+1/2) - math.log(total_e+27/2) for i in range(27)]
theta_e = [math.e ** theta_log_e[i] for i in range(27)]
df['e_theta'] = theta_e
df['e_theta_log'] = theta_log_e

In [4]:
df

characters  e_count   e_theta  e_theta_log
0           a      910  0.060169    -2.810606
1           b      168  0.011135    -4.497664
2           c      325  0.021510    -3.839238
3           d      332  0.021973    -3.817960
4           e     1594  0.105369    -2.250285
5           f      286  0.018933    -3.966861
6           g      264  0.017479    -4.046759
7           h      714  0.047216    -3.053017
8           i      838  0.055411    -2.892985
9           j       21  0.001421    -6.556547
10          k       56  0.003734    -5.590359
11          l      438  0.028977    -3.541240
12          m      310  0.020519    -3.886416
13          n      876  0.057922    -2.848663
14          o      975  0.064464    -2.741650
15          p      253  0.016752    -4.089236
16          q        8  0.000562    -7.484534
17          r      814  0.053825    -2.922026
18          s     1001  0.066182    -2.715346
19          t     1212  0.080126    -2.524160
20          u      403  0.026664    -3.624424
21          v      140  0.009285    -4.679393
22          w      234  0.015496    -4.167144
23          x       17  0.001156    -6.762399
24          y      209  0.013844    -4.279876
25          z        9  0.000628    -7.373308
26                2712  0.179250    -1.718974

In [5]:
print('theta_e =', np.round(df['e_theta'].values, 5).tolist())
log_theta_e_str = 'log_theta_e = ['
for i in np.round(df["e_theta_log"].values, 3).tolist():
    log_theta_e_str += 'e^{'+str(i) + '}, '
log_theta_e_str += ']'
print(log_theta_e_str)

theta_e = [0.06017, 0.01113, 0.02151, 0.02197, 0.10537, 0.01893, 0.01748, 0.04722, 0.05541, 0.00142, 0.00373, 0.02898, 0.02052, 0.05792, 0.06446, 0.01675, 0.00056, 0.05382, 0.06618, 0.08013, 0.02666, 0.00928, 0.0155, 0.00116, 0.01384, 0.00063, 0.17925]
log_theta_e = [e^{-2.811}, e^{-4.498}, e^{-3.839}, e^{-3.818}, e^{-2.25}, e^{-3.967}, e^{-4.047}, e^{-3.053}, e^{-2.893}, e^{-6.557}, e^{-5.59}, e^{-3.541}, e^{-3.886}, e^{-2.849}, e^{-2.742}, e^{-4.089}, e^{-7.485}, e^{-2.922}, e^{-2.715}, e^{-2.524}, e^{-3.624}, e^{-4.679}, e^{-4.167}, e^{-6.762}, e^{-4.28}, e^{-7.373}, e^{-1.719}, ]


### (3)

In [6]:
# Q3
# theta_j
df['j_count'] = count_character(j_list)
total_j = sum(count_character(j_list))
theta_log_j = [math.log(count_character(j_list)[i]+1/2) - math.log(total_j+27/2) for i in range(27)]
theta_j = [math.e ** theta_log_j[i] for i in range(27)]
df['j_theta'] = theta_j
df['j_theta_log'] = theta_log_j

# theta_s
df['s_count'] = count_character(s_list)
total_s = sum(count_character(s_list))
theta_log_s = [math.log(count_character(s_list)[i]+1/2) - math.log(total_s+27/2) for i in range(27)]
theta_s = [math.e ** theta_log_s[i] for i in range(27)]
df['s_theta'] = theta_s
df['s_theta_log'] = theta_log_s

In [7]:
df

characters  e_count   e_theta  e_theta_log  j_count   j_theta  j_theta_log  \
0           a      910  0.060169    -2.810606     1885  0.131766    -2.026731   
1           b      168  0.011135    -4.497664      155  0.010867    -4.522033   
2           c      325  0.021510    -3.839238       78  0.005486    -5.205580   
3           d      332  0.021973    -3.817960      246  0.017226    -4.061317   
4           e     1594  0.105369    -2.250285      861  0.060205    -2.810004   
5           f      286  0.018933    -3.966861       55  0.003879    -5.552296   
6           g      264  0.017479    -4.046759      200  0.014012    -4.267865   
7           h      714  0.047216    -3.053017      454  0.031762    -3.449481   
8           i      838  0.055411    -2.892985     1388  0.097033    -2.332700   
9           j       21  0.001421    -6.556547       33  0.002341    -6.057133   
10          k       56  0.003734    -5.590359      821  0.057409    -2.857547   
11          l      438  0.028977    -3.541240       20  0.001433    -6.548254   
12          m      310  0.020519    -3.886416      569  0.039799    -3.223920   
13          n      876  0.057922    -2.848663      811  0.056711    -2.869795   
14          o      975  0.064464    -2.741650     1304  0.091163    -2.395104   
15          p      253  0.016752    -4.089236       12  0.000874    -7.042950   
16          q        8  0.000562    -7.484534        1  0.000105    -9.163214   
17          r      814  0.053825    -2.922026      612  0.042804    -3.151130   
18          s     1001  0.066182    -2.715346      603  0.042175    -3.165933   
19          t     1212  0.080126    -2.524160      815  0.056990    -2.864878   
20          u      403  0.026664    -3.624424     1010  0.070617    -2.650478   
21          v      140  0.009285    -4.679393        3  0.000245    -8.315916   
22          w      234  0.015496    -4.167144      282  0.019742    -3.925000   
23          x       17  0.001156    -6.762399        0  0.000035   -10.261826   
24          y      209  0.013844    -4.279876      202  0.014151    -4.257939   
25          z        9  0.000628    -7.373308      110  0.007722    -4.863663   
26                2712  0.179250    -1.718974     1766  0.123449    -2.091923   

    s_count   s_theta  s_theta_log  
0      1695  0.104560    -2.257990  
1       133  0.008233    -4.799621  
2       608  0.037526    -3.282726  
3       644  0.039746    -3.225248  
4      1845  0.113811    -2.173217  
5       139  0.008603    -4.755658  
6       116  0.007184    -4.935832  
7        73  0.004533    -5.396437  
8       808  0.049860    -2.998542  
9       107  0.006629    -5.016232  
10        4  0.000278    -8.189645  
11      858  0.052943    -2.938536  
12      418  0.025809    -3.657046  
13      878  0.054177    -2.915507  
14     1175  0.072492    -2.624274  
15      393  0.024267    -3.718642  
16      124  0.007678    -4.869417  
17      961  0.059295    -2.825228  
18     1066  0.065770    -2.721585  
19      577  0.035614    -3.335014  
20      546  0.033702    -3.390189  
21       95  0.005889    -5.134597  
22        1  0.000093    -9.288258  
23       40  0.002498    -5.992421  
24      127  0.007863    -4.845606  
25       43  0.002683    -5.920962  
26     2728  0.168265    -1.782216

In [8]:
df.to_csv('Q23.csv')

In [9]:
print('theta_j =', np.round(df['j_theta'].values, 5).tolist())
print('theta_s =', np.round(df['s_theta'].values, 5).tolist())

theta_j = [0.13177, 0.01087, 0.00549, 0.01723, 0.0602, 0.00388, 0.01401, 0.03176, 0.09703, 0.00234, 0.05741, 0.00143, 0.0398, 0.05671, 0.09116, 0.00087, 0.0001, 0.0428, 0.04217, 0.05699, 0.07062, 0.00024, 0.01974, 3e-05, 0.01415, 0.00772, 0.12345]
theta_s = [0.10456, 0.00823, 0.03753, 0.03975, 0.11381, 0.0086, 0.00718, 0.00453, 0.04986, 0.00663, 0.00028, 0.05294, 0.02581, 0.05418, 0.07249, 0.02427, 0.00768, 0.0593, 0.06577, 0.03561, 0.0337, 0.00589, 9e-05, 0.0025, 0.00786, 0.00268, 0.16826]


In [10]:
log_theta_j_str = 'log_theta_j = ['
for i in np.round(df["j_theta_log"].values, 3).tolist():
    log_theta_j_str += 'e^{'+str(i) + '}, '
log_theta_j_str += ']'
print(log_theta_j_str)

log_theta_j = [e^{-2.027}, e^{-4.522}, e^{-5.206}, e^{-4.061}, e^{-2.81}, e^{-5.552}, e^{-4.268}, e^{-3.449}, e^{-2.333}, e^{-6.057}, e^{-2.858}, e^{-6.548}, e^{-3.224}, e^{-2.87}, e^{-2.395}, e^{-7.043}, e^{-9.163}, e^{-3.151}, e^{-3.166}, e^{-2.865}, e^{-2.65}, e^{-8.316}, e^{-3.925}, e^{-10.262}, e^{-4.258}, e^{-4.864}, e^{-2.092}, ]


In [11]:
log_theta_s_str = 'log_theta_s = ['
for i in np.round(df["s_theta_log"].values, 3).tolist():
    log_theta_s_str += 'e^{'+str(i) + '}, '
log_theta_s_str += ']'
print(log_theta_s_str)

log_theta_s = [e^{-2.258}, e^{-4.8}, e^{-3.283}, e^{-3.225}, e^{-2.173}, e^{-4.756}, e^{-4.936}, e^{-5.396}, e^{-2.999}, e^{-5.016}, e^{-8.19}, e^{-2.939}, e^{-3.657}, e^{-2.916}, e^{-2.624}, e^{-3.719}, e^{-4.869}, e^{-2.825}, e^{-2.722}, e^{-3.335}, e^{-3.39}, e^{-5.135}, e^{-9.288}, e^{-5.992}, e^{-4.846}, e^{-5.921}, e^{-1.782}, ]


### (4)

In [12]:
e10 = [read_file('e10.txt')]
count_e10 = count_character(e10)
print(count_e10)

[164, 32, 53, 57, 311, 55, 51, 140, 140, 3, 6, 85, 64, 139, 182, 53, 3, 141, 186, 225, 65, 31, 47, 4, 38, 2, 498]


### (5)

In [13]:
p_x_y = []
for l in language:
    col = l+'_theta_log'
    theta_log = [(count_e10[i] * df[col][i]) for i in range(27)]
    p_x_y_l = np.sum(theta_log)
    p_x_y.append(p_x_y_l)
    print(f'p(x|y={l})=e^{p_x_y_l}')

p(x|y=e)=e^-7841.865447060634
p(x|y=j)=e^-8771.43307907503
p(x|y=s)=e^-8467.282044010557


### (7)

In [14]:
def predict(count_list):
    theta = []
    pred = []
    for count in count_list:
        p_x_y=[]
        for l in language:
            col = l+'_theta_log'
            theta_log = [(count[i] * df[col][i]) for i in range(27)]
            p_x_y.append(sum(theta_log))
        theta.append(p_x_y)
    
    for t in theta:
        if t[0]>=t[1] and t[0]>=t[2]:
            p = 'e'
        elif t[1]>=t[0] and t[1]>=t[2]:
            p = 'j'
        elif t[2]>=t[0] and t[2]>=t[1]:
            p = 's'
        pred.append(p)
    return pred

In [15]:
e_count_list = []
j_count_list = []
s_count_list = []
for i in range(10,20):
    e_count_list.append(count_character(read_file("e"+str(i)+'.txt')))
    j_count_list.append(count_character(read_file("j"+str(i)+'.txt')))
    s_count_list.append(count_character(read_file("s"+str(i)+'.txt')))
count_list = [e_count_list, j_count_list, s_count_list]

predicted = []
predicted_labels = []
for i in range(3):
    predicted_label = predict(count_list[i])
    predicted.append(predicted_label)
    predicted_labels.append([language.index(e) for e in predicted_label])
predicted

[['e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e'],
 ['j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j'],
 ['s', 's', 's', 's', 's', 's', 's', 's', 's', 's']]

In [16]:
gt = [['e']*10, ['j']*10, ['s']*10]
ground_truth = []
for i in range(3):
   ground_truth.append([language.index(e) for e in gt[i]])

In [17]:
confusion_matrix = np.zeros((3,3))
for i in range(3):
    for j in range(len(predicted_labels[i])):
        p = predicted_labels[i][j]
        t = ground_truth[i][j]
        confusion_matrix[p][t] += 1

print("Confusion Matrix:\n", confusion_matrix)


Confusion Matrix:
 [[10.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 10.]]
